### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by devi20dc** [d3nbr0/aiocarrot#1]
When executing a file 
python3 ./consumer.py

An error occurs
    await self._channel.close()
AttributeError: 'NoneType' object has no attribute 'close'

The RabbitMQ itself works and is available.

**Comment by devi20dc** [comment]
How to remove auto_delete in a queue?

**Comment by d3nbr0** [comment]
Can you please show the code consumer.py?

**Comment by d3nbr0** [comment]
Closed due to inactivity
